### ISSUE TITLE
clang dependence

### ISSUE THREAD

**Issue by jianshu93** [wwood/hmmer-rs#1]
Hell Ben,

I can run it without error on Linux but it seems to rely on clang compiler (clang from LLMM). Similar to that of minimap2-rs (https://github.com/jguhlin/minimap2-rs), they removed dependence on clang, I do not know how. So happy it can be used now!

Jianshu

**Comment by wwood** [comment]
Hey,

Not sure I follow. Isn't clang required for rust overall?

-\-------------
Ben Woodcroft
Group leader, Centre for Microbiome Research, QUT
________________________________
From: Jianshu_Zhao ***@***.***>
Sent: Saturday, January 28, 2023 5:06:46 AM
To: wwood/hmmer-rs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wwood/hmmer-rs] clang dependence (Issue #1)


Hell Ben,

I can run it without error on Linux but it seems to rely on clang compiler (clang from LLMM). Similar to that of minimap2-rs (https://github.com/jguhlin/minimap2-rs), they removed dependence on clang, I do not know how. So happy it can be used now!

Jianshu

―

**Comment by jianshu93** [comment]
Hello Ben，


Check similar one here：https://github.com/jguhlin/minimap2-rs/issues/9

**Comment by wwood** [comment]
Oh I see, makes sense now.

I suppose this is an issue for libhmmer-sys not hmmer-rs right? Have you had a go at implementing the instructions you cite?
Thanks.

**Comment by jianshu93** [comment]
Yes it should be related to libhmmer-sys, I will try to report there then. I have not had at time to check and implement, but I will see what I can do.


Thanks,

Jianshu
